# permissions for end users to edit flexlbclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flexlbcluster-editor-role
rules:
- apiGroups:
  - crd.flexlb.flexlet.io
  resources:
  - flexlbclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.flexlb.flexlet.io
  resources:
  - flexlbclusters/status
  verbs:
  - get
