apiVersion: apps/v1
kind: Deployment
metadata:
  name: flexlb-kube-controller
  namespace: kube-system
  labels:
    app: flexlb-kube-controller
spec:
  selector:
    matchLabels:
      app: flexlb-kube-controller
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: flexlb-kube-controller
      labels:
        app: flexlb-kube-controller
    spec:
      serviceAccountName: flexlb-kube-controller
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
      containers:
      - name: flexlb-kube-controller
        image: ghcr.io/flexlet/flexlb-kube-controller:0.4.2
        args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        - --tls-ca-cert=/certs/ca.crt
        - --tls-client-cert=/certs/client.crt
        - --tls-client-key=/certs/client.key
        - --tls-insecure
        - --refresh-interval=30
        - --namespace=kube-system
        - --probe-pod-image=busybox
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - name: flexlb-client-certs
          mountPath: "/certs"
          readOnly: true
      volumes:
      - name: flexlb-client-certs
        secret:
          secretName: flexlb-client-certs
